// 笔记/Front-end/Vue/Demo/Todo list/src/components/TodoMain.vue
<template>
  <!-- This section should be hidden by default and shown when there are todos -->
  <section class="main">
    <input v-model="isCheckAll" id="toggle-all" class="toggle-all" type="checkbox" />
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <!-- v-for 遍历 -->
      <li :class="{completed: item.isDone}" v-for="item in list" :key="item.id">
        <div class="view">
          <input class="toggle" type="checkbox" :checked="item.isDone" @change="changeState(item.id)"/>
          <label>{{item.name}}</label>
          <button class="destroy" @click="del(item.id)"></button>
        </div>
        <input class="edit" value="Create a TodoMVC template" />
      </li>
    </ul>
  </section>
</template>

<script>
export default {
    props: {
        list: {
            type: Array,
            require: true
        }
    },
    methods: {
        //删除操作
        del(id) {
            // 派发事件
            this.$emit('del', id)
        },
        // 修改复选框状态
        changeState(id) {
            this.$emit('changeState', id)
        }
    },
    computed: {
        isCheckAll: {
          set(val) {
              console.log(val)
              this.$emit('changeAll', val)
          },
          get() {
              return this.list.every(v => v.isDone)
          },
        }
    }
}
</script>

<style>
</style>

// 笔记/Front-end/React/Demo/TodoMvc/components/TodoMain.jsx
import React, { Component } from 'react'
import propTypes from 'prop-types'

export default class TodoMain extends Component {
  // 添加 props 的校验
  static propTypes = {
    list: propTypes.array,
  }
  render() {
    const { list } = this.props
    return (
      <div>
        <section className="main">
          <input id="toggle-all" className="toggle-all" type="checkbox" />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {list.map((item) => (
              <li key={item.id} className={item.done ? 'completed' : ''}>
                <div className="view">
                  <input className="toggle" type="checkbox" checked={item.done} />
                  <label>{item.name}</label>
                  <button className="destroy"></button>
                </div>
                <input className="edit" value="Create a TodoMVC template" />
              </li>
            ))}
          </ul>
        </section>
      </div>
    )
  }
}
