// 笔记/Front-end/React/Demo/TodoMvc/components/TodoHeader.jsx
import axios from 'axios'
import React, { Component } from 'react'

export default class TodoHeader extends Component {
  state = {
    todoName: '',
  }
  render() {
    return (
      <div>
        <header className="header">
          <h1>todos</h1>
          <input
            className="new-todo"
            placeholder="What needs to be done?"
            autoFocus
            value={this.state.todoName}
            onChange={(e) => this.setState({ todoName: e.target.value })}
            onKeyUp={this.add}
          />
        </header>
      </div>
    )
  }
  add = async (e) => {
    // console.log(e.code)
    if (e.code === 'Enter') {
      // 校验
      if (!this.state.todoName.trim()) return
      // 发请求添加
      await axios.post('http://localhost:8888/todos', {
        name: this.state.todoName,
        done: false,
      })
      this.setState({
        todoName: '',
      })
      // 重新渲染
      this.props.getTodoList()
    }
  }
}

// 笔记/Front-end/Vue/Demo/Todo list/src/components/TodoHeader.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input v-model.trim="name" @keyup.enter="add" class="new-todo" placeholder="需要做些什么？" autofocus />
  </header>
</template>

<script>
export default {
    data(){
        return {
            name: ''
        }
    },
    methods: {
        add() {
            // console.log(this.name)
            // 判断不能输入空
            if(this.name === '') return
            this.$emit('add', this.name)
            // 清空
            this.name = ''
        }
    }
};
</script>

<style>
</style>
